from pydantic import BaseModel, Field

class FormReq(BaseModel):
    path: str = Field(..., description="Path URL", example="/")
    method: str = Field(..., description="Metode HTTP", example="GET")
    httpVersion: float = Field(..., description="Versi HTTP", example=1.1)
    headers_user_agent: str = Field(..., description="User Agent", alias="headers.user-agent", example="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36")
    headers_accept: str = Field(..., description="Header Accept", alias="headers.accept", example="*/*")
    headers_accept_encoding: str = Field(..., description="Header Accept-Encoding", alias="headers.accept-encoding", example="gzip")
    remotePort: int = Field(..., description="Remote Port", example=50326)
    protocol: str = Field(..., description="Protokol", example="http")
    duration: int = Field(..., description="Durasi", example=0)
    responseStatusCode: int = Field(..., description="Kode Status Respons", example=200)
    ip_v4: str = Field(..., description="Alamat IP v4", example="13.58.97.162")
    country: str = Field(..., description="Negara", example="United States")
    isp: str = Field(..., description="Penyedia Layanan Internet", example="Amazon.com, Inc.")
    org: str = Field(..., description="Organisasi", example="AWS EC2 (us-east-2)")
    mobile: bool = Field(..., description="Apakah Mobile", example=False)
    proxy: bool = Field(..., description="Apakah Proxy", example=False)
    hosting: bool = Field(..., description="Apakah Hosting", example=True)
    is_abuser: bool = Field(..., description="Apakah Abuser", example=False)
    is_attacker: bool = Field(..., description="Apakah Attacker", example=True)
    is_bogon: bool = Field(..., description="Apakah Bogon", example=False)
    is_cloud_provider: bool = Field(..., description="Apakah Cloud Provider", example=True)
    is_proxy: bool = Field(..., description="Apakah Proxy", example=False)
    is_relay: bool = Field(..., description="Apakah Relay", example=False)
    is_tor: bool = Field(..., description="Apakah Tor", example=False)
    is_tor_exit: bool = Field(..., description="Apakah Tor Exit", example=False)
    is_vpn: bool = Field(..., description="Apakah VPN", example=False)
    is_anonymous: bool = Field(..., description="Apakah Anonim", example=False)
    is_threat: bool = Field(..., description="Apakah Threat", example=True)
    msElapsedWithIP: int = Field(..., description="Waktu yang Telah Berlalu dengan IP", example=70128)
    headers_accept_language: str = Field(..., description="Header Accept-Language", example="")
    headers_upgrade_insecure_requests: float = Field(..., description="Header Upgrade-Insecure-Requests", example=1.0)
    headers_connection: str = Field(..., description="Header Connection", example="")
    headers_x_requested_with: str = Field(..., description="Header X-Requested-With", example="")
    headers_content_type: str = Field(..., description="Header Content-Type", example="")
    headers_content_length: float = Field(..., description="Header Content-Length", example=0)
    rawBody: str = Field(..., description="Raw Body", example="")
    class Config:
        populate_by_name = True